package merchants

// Directory are merchants people in the Dominican Republic pay: chains,
// utilities, the government and global services, as banks print them. The
// first that matches wins, so a more specific one goes before ("Uber Eats"
// before "Uber"). Words are matched whole, in order, without accents or
// punctuation: "uber eats" finds "UBER EATS-W*UBER EATS-" and "UBER*EATS".
var Directory = []Merchant{
	// Supermarkets and stores.
	{ID: "la-sirena", Name: "La Sirena", Words: []string{"la sirena", "tiendas la sirena"}},
	{ID: "nacional", Name: "Nacional", Words: []string{"sm nacional", "supermercado nacional", "supermercados nacional", "super nacional"}},
	{ID: "jumbo", Name: "Jumbo", Words: []string{"jumbo"}},
	{ID: "bravo", Name: "Bravo", Words: []string{"sm bravo", "supermercado bravo", "supermercados bravo"}, First: []string{"bravo"}},
	{ID: "pricesmart", Name: "PriceSmart", Words: []string{"pricesmart", "price smart"}},
	{ID: "plaza-lama", Name: "Plaza Lama", Words: []string{"plaza lama"}},
	{ID: "carrefour", Name: "Carrefour", Words: []string{"carrefour"}},
	{ID: "ole", Name: "Olé", Words: []string{"hiper ole", "hipermercado ole", "hipermercados ole", "supermercado ole"}},
	{ID: "pola", Name: "Pola", Words: []string{"supermercado pola", "supermercados pola"}},
	{ID: "ferreteria-americana", Name: "Ferretería Americana", Words: []string{"ferreteria americana"}},
	{ID: "ochoa", Name: "Ferretería Ochoa", Words: []string{"ferreteria ochoa"}},
	{ID: "ikea", Name: "IKEA", Words: []string{"ikea"}},
	{ID: "cuesta-libros", Name: "Cuesta Libros", Words: []string{"cuesta libros", "lib cuesta"}},
	{ID: "casa-cuesta", Name: "Casa Cuesta", Words: []string{"casa cuesta"}},
	{ID: "corripio", Name: "Corripio", Words: []string{"corripio"}},
	{ID: "jugueton", Name: "Juguetón", Words: []string{"jugueton"}},
	{ID: "zara", Name: "Zara", Words: []string{"zara"}},
	{ID: "bershka", Name: "Bershka", Words: []string{"bershka"}},
	{ID: "nike", Name: "Nike", Words: []string{"nike"}},
	{ID: "adidas", Name: "Adidas", Words: []string{"adidas"}},
	{ID: "payless", Name: "Payless", Words: []string{"payless"}},

	// Pharmacies, health and fitness.
	{ID: "farmacia-carol", Name: "Farmacia Carol", Words: []string{"farmacia carol", "farmacias carol", "farm carol", "fcia carol"}},
	{ID: "medicar", Name: "Medicar GBC", Words: []string{"medicar"}},
	{ID: "farmax", Name: "Farmax", Words: []string{"farmax"}},
	{ID: "los-hidalgos", Name: "Farmacia Los Hidalgos", Words: []string{"los hidalgos"}},
	{ID: "farma-value", Name: "Farma Value", Words: []string{"farma value"}},
	{ID: "referencia", Name: "Laboratorio Referencia", Words: []string{"lab ref", "laboratorio referencia", "laboratorios referencia"}},
	{ID: "amadita", Name: "Laboratorio Amadita", Words: []string{"amadita"}},
	{ID: "hospiten", Name: "Hospiten", Words: []string{"hospiten"}},
	{ID: "cedimat", Name: "Cedimat", Words: []string{"cedimat"}},
	{ID: "golds-gym", Name: "Gold's Gym", Words: []string{"golds gym", "gold s gym"}},
	{ID: "smart-fit", Name: "Smart Fit", Words: []string{"smart fit", "smartfit"}},
	{ID: "ars-universal", Name: "ARS Universal", Words: []string{"ars universal"}},
	{ID: "ars-humano", Name: "ARS Humano", Words: []string{"ars humano", "humano seguros"}},
	{ID: "ars-palic", Name: "ARS Palic", Words: []string{"palic"}},
	{ID: "senasa", Name: "SeNaSa", Words: []string{"senasa"}},
	{ID: "mapfre", Name: "Mapfre", Words: []string{"mapfre"}},

	// Fuel, roads and transport.
	{ID: "texaco", Name: "Texaco", Words: []string{"texaco"}},
	{ID: "shell", Name: "Shell", Words: []string{"shell"}},
	{ID: "sunix", Name: "Sunix", Words: []string{"sunix"}},
	{ID: "esso", Name: "Esso", Words: []string{"esso"}},
	{ID: "totalenergies", Name: "TotalEnergies", Words: []string{"totalenergies", "total energies"}},
	{ID: "axxon", Name: "Axxon", Words: []string{"axxon"}},
	{ID: "puma", Name: "Puma Energy", Words: []string{"puma energy"}},
	{ID: "propagas", Name: "Propagas", Words: []string{"propagas"}},
	{ID: "tropigas", Name: "Tropigas", Words: []string{"tropigas"}},
	{ID: "rd-vial", Name: "RD Vial", Words: []string{"rd vial", "rdvial"}},
	{ID: "uber-eats", Name: "Uber Eats", Words: []string{"uber eats", "ubereats"}},
	{ID: "uber", Name: "Uber", Words: []string{"uber"}},
	{ID: "didi", Name: "DiDi", Words: []string{"didi"}},
	{ID: "indrive", Name: "inDrive", Words: []string{"indrive", "indriver"}},
	{ID: "cabify", Name: "Cabify", Words: []string{"cabify"}},
	{ID: "apolo-taxi", Name: "Apolo Taxi", Words: []string{"apolo taxi"}},
	{ID: "pedidosya", Name: "PedidosYa", Words: []string{"pedidosya", "pedidos ya"}},

	// Telecom, utilities and the government.
	{ID: "claro", Name: "Claro", Words: []string{"claro"}},
	{ID: "altice", Name: "Altice", Words: []string{"altice"}},
	{ID: "wind", Name: "Wind Telecom", Words: []string{"wind telecom"}},
	{ID: "edesur", Name: "Edesur", Words: []string{"edesur"}},
	{ID: "edenorte", Name: "Edenorte", Words: []string{"edenorte"}},
	{ID: "edeeste", Name: "Edeeste", Words: []string{"edeeste"}},
	{ID: "caasd", Name: "CAASD", Words: []string{"caasd"}},
	{ID: "coraasan", Name: "Coraasan", Words: []string{"coraasan"}},
	{ID: "dgii", Name: "DGII", Words: []string{"dgii", "impuestos internos"}},
	{ID: "onapi", Name: "ONAPI", Words: []string{"onapi"}},
	{ID: "intrant", Name: "INTRANT", Words: []string{"intrant"}},

	// Restaurants and fun.
	{ID: "wendys", Name: "Wendy's", Words: []string{"wendys", "wendy s"}},
	{ID: "mcdonalds", Name: "McDonald's", Words: []string{"mcdonalds", "mcdonald s", "mc donalds", "mc donald s"}},
	{ID: "burger-king", Name: "Burger King", Words: []string{"burger king"}},
	{ID: "kfc", Name: "KFC", Words: []string{"kfc"}},
	{ID: "pizza-hut", Name: "Pizza Hut", Words: []string{"pizza hut"}},
	{ID: "dominos", Name: "Domino's", Words: []string{"dominos", "domino s"}},
	{ID: "papa-johns", Name: "Papa John's", Words: []string{"papa johns", "papa john s"}},
	{ID: "little-caesars", Name: "Little Caesars", Words: []string{"little caesars"}},
	{ID: "taco-bell", Name: "Taco Bell", Words: []string{"taco bell"}},
	{ID: "subway", Name: "Subway", Words: []string{"subway"}},
	{ID: "starbucks", Name: "Starbucks", Words: []string{"starbucks"}},
	{ID: "krispy-kreme", Name: "Krispy Kreme", Words: []string{"krispy kreme"}},
	{ID: "dunkin", Name: "Dunkin'", Words: []string{"dunkin"}},
	{ID: "chilis", Name: "Chili's", Words: []string{"chilis", "chili s"}},
	{ID: "fridays", Name: "TGI Fridays", Words: []string{"tgi fridays", "fridays"}},
	{ID: "pollos-victorina", Name: "Pollos Victorina", Words: []string{"victorina"}},
	{ID: "pala-pizza", Name: "Pala Pizza", Words: []string{"pala pizza"}},
	{ID: "pizzarelli", Name: "Pizzarelli", Words: []string{"pizzarelli"}},
	{ID: "adrian-tropical", Name: "Adrian Tropical", Words: []string{"adrian tropical"}},
	{ID: "barra-payan", Name: "Barra Payán", Words: []string{"barra payan"}},
	{ID: "applebees", Name: "Applebee's", Words: []string{"applebees", "applebee s"}},
	{ID: "outback", Name: "Outback", Words: []string{"outback"}},
	{ID: "johnny-rockets", Name: "Johnny Rockets", Words: []string{"johnny rockets"}},
	{ID: "dairy-queen", Name: "Dairy Queen", Words: []string{"dairy queen"}},
	{ID: "helados-bon", Name: "Helados Bon", Words: []string{"helados bon"}},
	{ID: "yogen-fruz", Name: "Yogen Früz", Words: []string{"yogen fruz"}},
	{ID: "dave-busters", Name: "Dave & Buster's", Words: []string{"dave busters", "dave and busters", "dave buster s"}},
	{ID: "hard-rock", Name: "Hard Rock Cafe", Words: []string{"hard rock"}},
	{ID: "caribbean-cinemas", Name: "Caribbean Cinemas", Words: []string{"caribbean cinemas"}},
	{ID: "palacio-del-cine", Name: "Palacio del Cine", Words: []string{"palacio del cine"}},

	// Subscriptions and online services.
	{ID: "netflix", Name: "Netflix", Words: []string{"netflix"}},
	{ID: "spotify", Name: "Spotify", Words: []string{"spotify"}},
	{ID: "disney-plus", Name: "Disney+", Words: []string{"disney plus", "disneyplus", "disney"}},
	{ID: "paramount-plus", Name: "Paramount+", Words: []string{"paramount"}},
	{ID: "max", Name: "Max", Words: []string{"hbo max", "hbomax", "hbo"}},
	{ID: "star-plus", Name: "Star+", Words: []string{"star plus", "starplus"}},
	{ID: "vix", Name: "ViX", Words: []string{"vix"}},
	{ID: "prime-video", Name: "Prime Video", Words: []string{"prime video", "primevideo"}},
	{ID: "amazon", Name: "Amazon", Words: []string{"amazon", "amzn"}},
	{ID: "youtube", Name: "YouTube", Words: []string{"youtube"}},
	{ID: "google", Name: "Google", Words: []string{"google"}},
	{ID: "apple", Name: "Apple", Words: []string{"apple com", "apple services", "apple"}},
	{ID: "microsoft", Name: "Microsoft", Words: []string{"microsoft", "msft"}},
	{ID: "xbox", Name: "Xbox", Words: []string{"xbox"}},
	{ID: "playstation", Name: "PlayStation", Words: []string{"playstation", "sony playstation"}},
	{ID: "steam", Name: "Steam", Words: []string{"steam games", "steampowered", "steam purchase"}},
	{ID: "nintendo", Name: "Nintendo", Words: []string{"nintendo"}},
	{ID: "openai", Name: "ChatGPT", Words: []string{"openai", "chatgpt"}},
	{ID: "anthropic", Name: "Claude", Words: []string{"claude ai", "anthropic"}},
	{ID: "xai", Name: "Grok", Words: []string{"grok", "xai"}},
	{ID: "oracle", Name: "Oracle", Words: []string{"oracle"}},
	{ID: "adobe", Name: "Adobe", Words: []string{"adobe"}},
	{ID: "canva", Name: "Canva", Words: []string{"canva"}},
	{ID: "dropbox", Name: "Dropbox", Words: []string{"dropbox"}},
	{ID: "github", Name: "GitHub", Words: []string{"github"}},
	{ID: "notion", Name: "Notion", Words: []string{"notion so"}},
	{ID: "zoom", Name: "Zoom", Words: []string{"zoom us", "zoom video"}},
	{ID: "duolingo", Name: "Duolingo", Words: []string{"duolingo"}},
	{ID: "crunchyroll", Name: "Crunchyroll", Words: []string{"crunchyroll"}},

	// Shopping online and travel.
	{ID: "temu", Name: "Temu", Words: []string{"temu"}},
	{ID: "shein", Name: "Shein", Words: []string{"shein"}},
	{ID: "aliexpress", Name: "AliExpress", Words: []string{"aliexpress"}},
	{ID: "ebay", Name: "eBay", Words: []string{"ebay"}},
	{ID: "walmart", Name: "Walmart", Words: []string{"walmart"}},
	{ID: "booking", Name: "Booking.com", Words: []string{"booking com", "booking"}},
	{ID: "airbnb", Name: "Airbnb", Words: []string{"airbnb"}},
	{ID: "expedia", Name: "Expedia", Words: []string{"expedia"}},
	{ID: "jetblue", Name: "JetBlue", Words: []string{"jetblue", "jet blue"}},
	{ID: "american-airlines", Name: "American Airlines", Words: []string{"american airlines", "american air"}},
	{ID: "arajet", Name: "Arajet", Words: []string{"arajet"}},
	{ID: "copa", Name: "Copa Airlines", Words: []string{"copa airlines", "copa air"}},
	{ID: "delta", Name: "Delta", Words: []string{"delta air"}},
	{ID: "united", Name: "United Airlines", Words: []string{"united airlines", "united air"}},
	{ID: "spirit", Name: "Spirit", Words: []string{"spirit air"}},
	{ID: "avianca", Name: "Avianca", Words: []string{"avianca"}},
	{ID: "iberia", Name: "Iberia", Words: []string{"iberia"}},
	{ID: "bm-cargo", Name: "BM Cargo", Words: []string{"bm cargo"}},
	{ID: "vimenca", Name: "Vimenca", Words: []string{"vimenca"}},
}
